### ISSUE TITLE
Can't convert anything but Grumpycat.rgba

### ISSUE THREAD

**Issue by adrianmkofficial** [eugeneware/jpeg-js#10]
Hey,

I currently have the issue, that the JPG Encoder doesn't work with self-made RGBA Files, except for the bundled grumpycat.rgba. Not even the apsara.rgba works. Besides that no other Image works.

Any Help would be appreciated!

Thanks.

**Comment by metabench** [comment]
What do you men by self-made RGBA files?

**Comment by adrianmkofficial** [comment]
Well I can't convert anything but that grumpycat.rgba. How do I use it with other images?

**Comment by patrickhulce** [comment]
The `.rgba` files are not a typical use case outside of the tests as you should not be storing uncompressed pixel data in an unstructured format that lacks width and height information. 

That being said you could try to reconstruct image data coming from a file you've written like so

```js
const jpeg = require('jpeg-js')
jpeg.encode({
  width: 100,
  height: 100,
  data: fs.readFileSync('./my-image.rgba'),
})
```

**Comment by patrickhulce** [comment]
Closing this as inactive, but feel free to reach out again if you still have trouble.
