### ISSUE TITLE
Support for JPEG's with Color Space CMYK

### ISSUE THREAD

**Issue by canvas-manik** [eugeneware/jpeg-js#13]
Hi,

I am using Jimp package which internally uses this package for Jpeg files. One issue I see that while compacting the images, the images with ColorSpace as CMYK, it blackens the image. Can you help in support for this kind of images.

I had logged the issue with Jimp here https://github.com/oliver-moran/jimp/issues/88 

Regards,
Manik Mittal

**Comment by benwiley4000** [comment]
Hey @canvas-manik I believe this issue has been fixed by #16. Feel free to re-open if you believe that's not the case! 🙂
