### ISSUE TITLE
Can i use it on react native?

### ISSUE THREAD

**Issue by fabobadi** [eugeneware/jpeg-js#19]
Hi,

Im trying to use jpeg-js with RNFS (https://github.com/johanneslumpe/react-native-fs) in this way:

```
RNFS.readFile(path).then(file => {
      console.log(file);
      const rawImageData = jpeg.decode(file);
      console.log(new Buffer(rawImageData).toString('base64'));
    });
```

Bur when I try his, i get this error.
![image](https://cloud.githubusercontent.com/assets/17772625/16181301/b376c82a-366f-11e6-8665-f4b08be433f7.png)
Is possible to use this library to read an image and get a bitmap, specifically I am trying to do analysis pixel by pixel images 

Thanks

**Comment by patrickhulce** [comment]
Hey @fabobadi have you already sorted this out? From the code you've posted it's not clear what you're trying to do. `rawImageData` should be an object that looks like the following and would not be very useful base64 encoded even if it succeeded. 
```js
{
  width: 2,
  height: 2,
  data: [
    /* first pixel*/ r, g, b, a, /* second pixel*/  r, g, b, a
    /* third pixel*/ r, g, b, a, /* fourth pixel*/  r, g, b, a
  ]
}
```

**Comment by patrickhulce** [comment]
Closing this as inactive, but feel free to reach out again if you still have trouble.

**Comment by SeJV** [comment]
I have the same Problem. 
When storing the jpg as base64 and read the file with:
```
const imgBase64 = RNFS.readFile(uri, 'base64');
jpeg.decode(imgBase64); 
```
Results in: [Error: SOI not found]

**Comment by patrickhulce** [comment]
@SeJV you can't call `jpeg.decode` on a base64 string, you'll need to convert it to a Buffer/Uint8Array first (something like https://gist.github.com/borismus/1032746)

**Comment by Termtime** [comment]
Commenting for anyone that wants to use this package in react-native, the package already supports non-node environments if you use the `useTArray: true` option when using `jpeg`, I will leave an example of reading a QR code from a gallery's jpeg image here:

```
import jpeg from 'jpeg-js';
import { Buffer } from 'buffer';
import { launchImageLibrary } from 'react-native-image-picker';

const readQRFromGallery = () => {
  launchImageLibrary(
      {
        selectionLimit: 1,
        mediaType: 'photo',
        includeBase64: true,
      },
      ({ didCancel, assets, errorCode }) => {
        if (didCancel || errorCode || !assets || assets.length === 0) {
         // Handle errors here, or separately
          return;
        }
        const image = assets[0];
        const base64Buffer = Buffer.from(image.base64!, 'base64');
        let pixelData;
        let imageBuffer;
        if (image.type === 'image/jpeg') {
          pixelData = jpeg.decode(base64Buffer, { useTArray: true });
          imageBuffer = pixelData.data;
        } else {
          return;
        }
        const data = Uint8ClampedArray.from(imageBuffer);

        ...
       // Then you can use the data object with something like jsQR to read the string data of the qr code

      }
    );
  };
}
```
