### ISSUE TITLE
how to read jpeg from url and then decode it?

### ISSUE THREAD

**Issue by slidenerd** [eugeneware/jpeg-js#22]
Thank for the awesome work on this library first of all, I read the documentation and dont see any decode options from the url directly. I have a JPG image and was wondering what would be the right way to decode it from a url into an RGBA 1d array for processing,  any suggestions are highly appreciated

**Comment by DoomTay** [comment]
You could do something like this

request({url:"http://www.example.com/file.jpg",encoding:null},function(err,response,buffer)
{
	var rawImageData = jpeg.decode(buffer).data;
	
	console.log(rawImageData);
})

**Comment by benwiley4000** [comment]
Thanks @slidenerd for the question. Handling HTTP or file requests is a bit beyond the current scope of this library, but the [get-pixels](https://github.com/scijs/get-pixels) library, which relies on jpeg-js, likely provides what you're asking for!
