### ISSUE TITLE
Colors for "RGB" JPEGs are color shifted

### ISSUE THREAD

**Issue by DoomTay** [eugeneware/jpeg-js#23]
For example, http://web.archive.org/web/20020326220359id_/http://www2.warnerbros.com:80/zeta/borgs/domains/guard.emb has messed up colors without any alterations having been done.

```
request({url:"http://web.archive.org/web/20020326220359id_/http://www2.warnerbros.com:80/zeta/borgs/domains/guard.emb",encoding:null},function(err,response,buffer)
{
	var rawImageData = jpeg.decode(buffer).data;
	
	//Should be 86 86 248, a somewhat purplish blue. Instead it's 254 14 11
	console.log(rawImageData[0],rawImageData[1],rawImageData[2]);
})
```

I think what is happening is that it reads YCbCr values and for some reason converts them to RGB and caps them

Here are some other images with the same problem

http://web.archive.org/web/20010801155449id_/http://www2.warnerbros.com/zeta/borgs/objects/ro.sprite

http://web.archive.org/web/20020109174604id_/http://www.cyberworldcorp.com/Gallery/worlds/olympiad/objects/p_horse.sprite

https://bugs.chromium.org/p/chromium/issues/attachment?aid=53847

### before

![guard.emb.jpg](https://i.imgur.com/LJG3GAv.jpg)

### after

![guard.emb.reencoded.jpg](https://i.imgur.com/BIhJkYn.jpg)

### before

![ro.sprite.jpg](http://i.imgur.com/KOd0tL7.jpg)

### after

![ro.sprite.reencoded.jpg](http://i.imgur.com/jkFtsYc.jpg)

### before

![p_horse.sprite.jpg](http://i.imgur.com/Euq2qCa.jpg)

### after

![p_horse.sprite.reencoded.jpg](http://i.imgur.com/kLZE4Dn.jpg)

### before

![image_processed00001.jpg](http://i.imgur.com/BlsMb7N.jpg)

### after

![image_processed00001.reencoded.jpg](http://i.imgur.com/NGDllZh.jpg)

**Comment by benwiley4000** [comment]
@DoomTay thanks for flagging this issue! Could you confirm it still exists after recent updates?

We'd definitely accept a PR to address this if the issue still persists.

**Comment by DoomTay** [comment]
I can confirm it still exists as of version 0.3.3

**Comment by benwiley4000** [comment]
thanks!

**Comment by DoomTay** [comment]
After some digging, I realized that the "problem images" have an Adobe color transform of 0. This may be the culprit, but I cannot verify, as I don't know how to find other JPEGs with a color transform of 0

**Comment by benwiley4000** [comment]
How did you come across the problem images? I wouldn't have even known they were jpegs, if you hadn't told me 😛

**Comment by DoomTay** [comment]
They are assets used in an old proprietary system from a now defuct company meant for "Creating virtual worlds" known as QBORGs

It all started sometime in 2015 when I tried to re-find [a game based on the second Pokemon movie](http://web.archive.org/web/20061105053936/http://p2kmovie.warnerbros.com/worlds.html). I thought I would try playing through it for the sake of nostalgia, but found that there was too much content missing to the point of unplayability.

Sometime in November, I thought I'd try looking into what makes the QBORG tick, while [emulating it via Javascript](https://github.com/DoomTay/jsborg). This involved discovering, among other things, that game sprites were just PNGs or JPEGs with some extra stuff.

Fast forward sometime later, I stumbled upon [JanusVR](http://janusvr.com/), a more recent project that had the aim of "transforming the web" into a 3-dimensional multiverse. I thought I'd try and "port" the QBORG to the JanusVR system. Turns out that goal would mean on-the-fly, server-side room generation and image manipulation

I was already pretty comfortable with node.js, so I did some research on what modules and such I would need, and found that for image manipulation, [jimp](https://github.com/oliver-moran/jimp) was probably the best to use, if only because it wasn't a wrapper for some other program or required some alternate version of node to install.

And that's how I found out these "unusual" type of JPEGs come out weird when processed through jpeg-js

**Comment by benwiley4000** [comment]
Wow nice - sounds like I missed out on that game when it came out!! :) The age of the system probably helps sort of explain why they were masking jpegs with non-standard extensions.

Do you have any way deployed version of your tool which can be used with e.g. the Pokemon game you mentioned? I'd be curious to test it out (even if the sprites are oddly re-colored 😛 ).

As for the bug, I'll keep my eyes open. The color transform 0 is an interesting lead - if you find out anything else please let us know.

**Comment by DoomTay** [comment]
Sadly not. You *could* just download that to your hard drive, then use a mass downloading tool like downThemAll to download everything under that path. Content under http://web.archive.org/web/*/http://www2.warnerbros.com/zeta/borgs/* or http://web.archive.org/web/*/http://www.cyberworldcorp.com/Gallery/worlds/olympiad/*

It should be noted that these images can be viewed in a browser and other image viewers, at least if you rename the extension to .jpg, and the colors come out normal

**Comment by benwiley4000** [comment]
Thanks. I was able to download the `.sprite` assets and produce before and after versions, which I'll attach to your first post in this thread.

**Comment by DoomTay** [comment]
Thank you. I replaced the first link with an .emb file from a different QBORG project, to demonstrate that this isn't limited to `.sprite` files. I regret not making it clear before what exactly was happening with the output, or that the images appear just fine in other viewers.

Curiously, [jpg-stream](https://github.com/devongovett/jpg-stream) has no trouble handling these sort of JPEGs

**Comment by benwiley4000** [comment]
I saw you updated the title - most jpg images would be RBG-encoded, so I'm a bit confused by your edit.

**Comment by DoomTay** [comment]
Oh? I thought most JPEGs would use YCbCr.

I'm not sure how to categorize, at the very least, the bottom-most image. It came from https://bugs.chromium.org/p/chromium/issues/detail?id=115287 where a commenter referred to the image as "an RGB-JPEG image used by Adobe"

**Comment by benwiley4000** [comment]
Yeah, sorry, you're right 😛 forget what I said. Thanks for helping to track this down!!

**Comment by Qti3e** [comment]
Hi
It's still present and I want to use it in some other project, and having the same output as using browser's canvas is very important to me.
Do you have any short time solution or a hack to make this work?
Thanks : )

**Comment by DoomTay** [comment]
You can sort of fix it with this

```node
image.scan(0, 0, image.bitmap.width, image.bitmap.height, function (x, y, i) { var r = this.bitmap.data[i + 0]; var g = this.bitmap.data[i + 1]; var b = this.bitmap.data[i + 2]; if(image._originalMime == "image/jpeg") { this.bitmap.data[i + 0] = (0.299 * r) + (0.587 * g) + (0.114 * b); this.bitmap.data[i + 1] = 128 - (0.168736 * r) - (0.331264 * g) + (0.5 * b); this.bitmap.data[i + 2] = 128 + (0.5 * r) - (0.418688 * g) - (0.081312 * b); } })
```

but the end result won't be perfect

**Comment by Qti3e** [comment]
Oh...! It made the situation even worse than what it was!
What happened with our fix is this:
![image](https://user-images.githubusercontent.com/13242052/36848520-b780cfc0-1d76-11e8-9ea2-937d0bb394b9.png)

```js
const jpeg = require("jpeg-js")
const jpegData = fs.readFileSync('grumpycat.jpg');
const image = jpeg.decode(jpegData, true)
for(let i = 0;i < image.data.length;i += 4){
	r = image.data[i + 0]
	g = image.data[i + 1]
	b = image.data[i + 2]
	image.data[i + 0] = (0.299 * r) + (0.587 * g) + (0.114 * b);
	image.data[i + 1] = 128 - (0.168736 * r) - (0.331264 * g) + (0.5 * b);
	image.data[i + 2] = 128 + (0.5 * r) - (0.418688 * g) - (0.081312 * b);
}
```

What actually happens without your fix is this:
![image](https://user-images.githubusercontent.com/13242052/36849252-c5cf0680-1d78-11e8-8afb-3842cb53d722.png)
Any idea where should I look for root of this bug?

**Comment by DoomTay** [comment]
Like I said, the fix isn't perfect.

Like I said in the beginning, the shifted colors is most likely from the package taking an Adobe RGB jpeg and doing a conversion it didn't need to and then capping the pixel values. The wonky colors from the fix would be a side effect of that capping.

The other possibility is that the input isn't an Adobe RGB type.

Can you upload the original image for comparison?

**Comment by Qti3e** [comment]
I use the same image as you are using as demo ([grumpycat.jpg](https://raw.githubusercontent.com/eugeneware/jpeg-js/master/test/fixtures/grumpycat.jpg))

```
$ file grumpycat.jpg 
grumpycat.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CS5 Macintosh, datetime=2012:12:03 12:13:22], baseline, precision 8, 320x180, frames 3
```

**Comment by DoomTay** [comment]
Just as I suspected

grumpycat.jpg is NOT an Adobe RGB JPEG. If it was, it would have a color transform of 0.

If the colors come out wonky with that image without my fix, then the problem lies elsewhere

**Comment by Qti3e** [comment]
That image loads without your fix and its color difference are not detectable by human eyes but the RGB values of that image are shifting a little bit (for example 65 -> 64, 42->41, 88->89, ...)
Your fix is just a YCbCr to RGB conversion and of course, that conversion happened by parser itself.

**Comment by DoomTay** [comment]
Yeah, that seems to be a completely separate problem from what this thread is about

**Comment by Qti3e** [comment]
Ok, thanks for your time.
 I'll start an issue at [jpgjs](https://github.com/notmasteryet/jpgjs).

**Comment by DoomTay** [comment]
Well it turns out that #39 fixes this issue, provided that `colorTransform` is set to `false`

**Comment by patrickhulce** [comment]
we believe #39 + #64 fixes this issue. if there are still issues with drastic color reproduction mistakes please feel free to chime back in with example files for us to add to the test suite :)
