### ISSUE TITLE
test directory in npm

### ISSUE THREAD

**Issue by jlami** [eugeneware/jpeg-js#33]
When looking through node_modules for a project of mine, looking for large packages, I saw that your package has a test directory with 4.3MB of data in it. Maybe you could include a .npmignore or only whitelist the files in lib and index.js with package.json "files"? Because your package could be as small as 60kb or something.

**Comment by patrickhulce** [comment]
great point thanks for highlighting @jlami!

**Comment by patrickhulce** [comment]
new bundle size using `pkgfiles` 🎉 

```
$ pkgfiles

PATH             SIZE     %
.npmignore       14 B     0%
.travis.yml      75 B     0%
index.js         136 B    0%
package.json     671 B    1%
CONTRIBUTING.md  1.23 kB  2%
LICENSE          1.45 kB  2%
README.md        6.1 kB   9%
lib/encoder.js   20.7 kB  32%
lib/decoder.js   34 kB    53%

DIR              SIZE     %
lib/             54.8 kB  85%
.                64.4 kB  100%

PKGFILES SUMMARY
Publishable Size                ~64.4 kB
Number of Directories           2
Number of Files                 9
```

**Comment by jlami** [comment]
nice, excellent result :)
