### ISSUE TITLE
Can we decode base64 images directly?

### ISSUE THREAD

**Issue by netgfx** [eugeneware/jpeg-js#35]
I am sending base64 encoded images to the server, how can I get rawImageData from them. Preferably without saving them into the filesystem first.

Thanks!

**Comment by patrickhulce** [comment]
hey @netgfx yeah you should be able to with something like the following

```js
const jpeg = require('jpeg-js')
const jpegData = Buffer.from(theBase64String, 'base64')
const rawImageData = jpeg.decode(jpegData)
```

**Comment by netgfx** [comment]
I tried that but got `jpg crash SOI not found undefined` maybe because I'm using the FileReader.readAsDataURL method?
Could I use the following and try to decode it same way?
https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsArrayBuffer

**Comment by patrickhulce** [comment]
That error means the buffer you tried to decode is not actually a JPEG. Are you sure what you're sending to the server is a real JPEG as base64 string? I'd try to debug by making sure your client-side code is producing valid base64 strings first. Use DevTools to take the output of `FileReader.readAsDataURL`, copy to clipboard, and validate with some online tool like https://www.base64decode.org/

**Comment by netgfx** [comment]
do I need to remove `data:image/jpeg;base64,` from the produced string?

**Comment by netgfx** [comment]
That was the problem after all, all working now!
