### ISSUE TITLE
Offload encoding to a Web Worker

### ISSUE THREAD

**Issue by kentmw** [eugeneware/jpeg-js#40]
A while back I asked the question, "Is it possible to generate an image (blob or data-url) in a web worker from a canvas context's getImageData?" [My SO question](https://stackoverflow.com/questions/35026647/is-it-possible-to-generate-an-image-blob-or-data-url-in-a-web-worker-from-a-ca)

Using the encode.js file from this library, I was able to do exactly that. I published an npm package [here](https://www.npmjs.com/package/jpeg-web-worker) and the associated github project [here](https://github.com/kentmw/jpeg-web-worker).

Would it make sense to add this functionality to this project?

**Comment by patrickhulce** [comment]
Thanks for filing and offering @kentmw! I'm not sure it makes sense to include this in jpeg-js though. This library is used in a variety of environments where it wouldn't be applicable, so keeping the feature set focused and small makes more sense here.
