### ISSUE TITLE
SOI not found

### ISSUE THREAD

**Issue by mparpaillon** [eugeneware/jpeg-js#41]
Hi,
I'm using image-hash, a library which uses jpeg-js and I've encountered an issue with this lib.
When trying to hash some images I get this:

```cli
/Volumes/Crypt/www/project/node_modules/jpeg-js/lib/decoder.js:597
        throw "SOI not found";
        ^
SOI not found
```

For instance with this URL: https://i.pinimg.com/originals/6c/15/55/6c1555fe2fd5db94213a6629ae589068.jpg

Script to reproduce:

```js
const imageHash = require('image-hash');

imageHash('https://i.pinimg.com/originals/6c/15/55/6c1555fe2fd5db94213a6629ae589068.jpg', 8, false, function(error, hash) {
  if (error) {
    console.error(error);
  }
  else {
    console.log(hash);
  }
});
```

Apparently, for some files, it can't find the SOI (Start of file), I don't know why.

https://github.com/eugeneware/jpeg-js/blob/master/lib/decoder.js#L597

If the "fileMarker" is different than 0xFFD8 then it fails...
Any idea ?
Should I edit the jpg to be sure to have a SOI ? How ?

Thanks a lot
Cheers

**Comment by mparpaillon** [comment]
Apparently, I just got a Access denied so it failed. My bad

**Comment by eymiha** [comment]
In case anyone gets this error, make sure that you're passing a Uint8Array buffer. If you happen to pass base64 data, it won't get decoded correctly.

It's an easy mistake to make. When you're displaying the jpeg data in an img, most of the examples I've seen deal with base64 exclusively. A quick conversion is all you need to correctly format the data to hand off to jpeg.decode.
