### ISSUE TITLE
Encode APP1 markers for EXIF metadata

### ISSUE THREAD

**Issue by hipstersmoothie** [eugeneware/jpeg-js#44]
I would like to be able to encode exif data into the buffer returned by `jpeg.encode`

**Comment by patrickhulce** [comment]
I've played with this on my own, and I think it's highly unlikely we'll incorporate this directly into jpeg-js. The complexity required for handling EXIF data properly is quiet high. 

If you're looking to do this, I'd suggest using another library like https://github.com/hMatoba/piexifjs to inject the EXIF buffer into whatever is generated by jpeg-js.

**Comment by Slyke** [comment]
Well this looks like it could work. I'll give it a go. Couldn't this be added into jpeg-js though, instead of writing from scratch?

**Comment by hipstersmoothie** [comment]
The buffer injection would be a nice feature for jpeg-js. I don't see many situations where jimp would need to modify the exif data at all.

**Comment by patrickhulce** [comment]
Yeah, sounds good. I'll try to put together a PR and run it by you folks for the API

**Comment by patrickhulce** [comment]
I haven't forgotten about this, I have a branch locally, just need to find some time in my travels to put it up sorry :)
