### ISSUE TITLE
JPEG size increase on save

### ISSUE THREAD

**Issue by hipstersmoothie** [eugeneware/jpeg-js#45]
```js
const fs = require('fs')
const jpeg = require('jpeg-js');

const buffer = fs.readFileSync('./exampleImages/npm.jpg')
const jpg = jpeg.decode(buffer)

const outBuffer = jpeg.encode(jpg, 100)

fs.writeFileSync('test.jpg', outBuffer.data)

console.log(buffer.byteLength, jpg.data.byteLength, outBuffer.data.byteLength)
```

OUTPUT:
```
20259 2764800 87636
```

it gets almost 4 times bigger!

**Comment by patrickhulce** [comment]
@hipstersmoothie quality 100 is highly impractical for normal usage and is expected to result in ridiculous file sizes. 85-90 is more reasonable with a max or ~95 for high quality use cases. How was that JPEG originally encoded?

**Comment by hipstersmoothie** [comment]
I'm not quite sure actually 
![npm](https://user-images.githubusercontent.com/1192452/43539125-d1960a4a-9578-11e8-877e-bf21fedc2763.jpg)

**Comment by patrickhulce** [comment]
Not to dispute the encoding problems (it's definitely not the best encoder out there), but that is the sort of image that is the textbook case for png over jpeg :)

Do you have some example photographs, not text, that really suffer from ~95 quality? That'd be a bit easier to motivate improvements and provide a good test case.

**Comment by hipstersmoothie** [comment]
@patrickhulce i used a more jpeggy image and it seems to work better. 

Can I ask what png over jpeg is and how you recognized it? I can't seem to find the concept on google. 

I'll close this as it seems to work better on pure pictures
