### ISSUE TITLE
Errors thrown as strings

### ISSUE THREAD

**Issue by agenouel** [eugeneware/jpeg-js#50]
In lib/decoder.js, on 3 different lines, decoding errors as throws as strings, which ends in script crash when using jimp as it tries to add information on error. Is it a normal behavior or a coding error ?

https://github.com/eugeneware/jpeg-js/blob/master/lib/decoder.js#L872
https://github.com/eugeneware/jpeg-js/blob/master/lib/decoder.js#L914
https://github.com/eugeneware/jpeg-js/blob/master/lib/decoder.js#L971

Tested with version 0.3.4

**Comment by patrickhulce** [comment]
Ah thanks for filing @agenouel! https://github.com/eugeneware/jpeg-js/commit/e6955d8954690eaeafb2dbcb0cebd6aa669e820e got most of them but missed some it seems :)

we'd welcome a fix for this

**Comment by agenouel** [comment]
Do I have the need rights to push a branch and make the pull request ?

**Comment by patrickhulce** [comment]
To push a branch, yes but to fork and open a PR no :)

**Comment by agenouel** [comment]
@patrickhulce I must be doing something wrong as I receive a "permission denied" when pushing my branch...

**Comment by patrickhulce** [comment]
Oh sorry I misunderstood your comment before the edit! You do not have the permissions necessary to push to this repo, but you should be able to fork it and open a PR.

**Comment by agenouel** [comment]
fork, fix and PR done ;)
