### ISSUE TITLE
How to resize width and height when encoding the jpeg?

### ISSUE THREAD

**Issue by endmaster0809** [eugeneware/jpeg-js#69]
I got decoded buffer from the jpeg.
The decoded JSON data is 
{
   width: 1700,
   height: 690,
   data: ...
}
I would like to encode it with keeping aspect ratio and max side to 1500.
I tried to it with hard coding but got bad image.

Is this out of jpeg-js library issue?

Result file is below: 

![result](https://user-images.githubusercontent.com/57788423/81514664-35713880-92e5-11ea-877d-884fe4557dd6.jpg)

**Comment by patrickhulce** [comment]
This is not what jpeg-js is for. JPEG encoding is the process of converting raw pixel data to a compressed JPEG buffer.

You're looking for a higher level image manipulation library, specifically resizing. Try [jimp](https://www.npmjs.com/package/jimp) which uses jpeg-js under the hood.
