### ISSUE TITLE
SOI not found (start of the image) jpeg-js. React-native

### ISSUE THREAD

**Issue by Dirie** [eugeneware/jpeg-js#74]
Hi,
Can anyone help me find this error:

Error: SOI not found .... _(SOI : start of the image)_
It returns this error whenever I use the function  **jpeg.decode(rawImage,true)**
the path of my image( which is  **base64** variable) is:

_file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252FDermaSom-87c250ab-f6ce-490d-b594-9b28ce51713f/Camera/83991dbd-9fd0-4983-9071-5e9a0cf94fe0.jpg_

my code is here

  ```
const imageToTensor = (base64) => {
    const rawImageData = tf.util.encodeString(base64, "base64");
    const TO_UINT8ARRAY = true;
    const { width, height, data } = jpeg.decode(rawImageData, TO_UINT8ARRAY);
    const buffer = new Uint8Array(width * height * 3);
    let offset = 0; // offset into original data
    for (let i = 0; i < buffer.length; i += 3) {
      buffer[i] = data[offset];
      buffer[i + 1] = data[offset + 1];
      buffer[i + 2] = data[offset + 2];
      offset += 4;
    }
    return tf.tensor3d(buffer, [height, width, 3]);
  };
```

**Comment by patrickhulce** [comment]
> Error: SOI not found .... (SOI : start of the image)

That error means you're not passing `jpeg-js` a JPEG buffer.

> the path of my image( which is base64 variable) is:
file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252FDermaSom-87c250ab-f6ce-490d-b594-9b28ce51713f/Camera/83991dbd-9fd0-4983-9071-5e9a0cf94fe0.jpg

`jpeg-js` doesn't accept file paths, it takes a buffer. Read this file from the filesystem with the [`fs` module](https://nodejs.org/api/fs.html) in node or [the `FileReader` in browser](https://developer.mozilla.org/en-US/docs/Web/API/FileReader).

**Comment by Dirie** [comment]
> > Error: SOI not found .... (SOI : start of the image)
> 
> That error means you're not passing `jpeg-js` a JPEG buffer.
> 
> > the path of my image( which is base64 variable) is:
> > file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252FDermaSom-87c250ab-f6ce-490d-b594-9b28ce51713f/Camera/83991dbd-9fd0-4983-9071-5e9a0cf94fe0.jpg
> 
> `jpeg-js` doesn't accept file paths, it takes a buffer. Read this file from the filesystem with the [`fs` module](https://nodejs.org/api/fs.html) in node or [the `FileReader` in browser](https://developer.mozilla.org/en-US/docs/Web/API/FileReader). (Sounds like you're react-native so maybe this is what you want https://www.npmjs.com/package/react-native-fs ?)

yeah, I passed a **buffer** variable  to the function **jpeg.decode(rawImageData, TO_UINT8ARRAY)**.  A variable rawImageData is a buffer not a file path and it returns **SOI not found error** still.  

the line bellow encodes a string to a buffer:
`const rawImageData = tf.util.encodeString(base64, "base64");`

**Comment by patrickhulce** [comment]
In your original issue you said...

> the path of my image( which is base64 variable) is
file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252FDermaSom-87c250ab-f6ce-490d-b594-9b28ce51713f/Camera/83991dbd-9fd0-4983-9071-5e9a0cf94fe0.jpg

But now you're saying the value of `base64` variable is not the file path? If it is *anything* other than the base64-encoded *image bytes* then this function won't work.

> the line bellow encodes a string to a buffer:
const rawImageData = tf.util.encodeString(base64, "base64");

It does, but turning a file path string into a buffer doesn't make it usable to `jpeg-js`. This library operates on a *buffer of an image file* not a buffer of the *path* to an image file.

**Comment by Dirie** [comment]
It worked. Thank you!
you saved my day.
