### ISSUE TITLE
SOI not found  jpeg-js with react-native-image-picker

### ISSUE THREAD

**Issue by zuntilZ** [eugeneware/jpeg-js#78]
```
const Buffer = require('buffer').Buffer;
global.Buffer = Buffer;
const  RNFS = require('react-native-fs');

  ImagePicker.launchImageLibrary({ mediaType: 'photo'},
(response) => {
    var base64 = response.data;
	var path = response.path;
	
	// check exists path and read file again
	RNFS.exists(path).then((exists) => {
	  if (exists) {
		RNFS.readFile(path, 'base64').then((res) => {
		// convert base64 to buffer
		   var jpegData = Buffer.from(res, 'base64'); 
		   
		   // Error DEOCDE : SOI  not found
		   var result = jpeg.decode(jpegData); 
		});
	  }
	});
});
```
i using react native  , react-native-image-picker ,  jpeg-js , buffer , react-native-fs ,jsQR

**Comment by patrickhulce** [comment]
Thanks for filing @zuntilZ! That means the provided buffer is not a valid JPEG.

**Comment by zuntilZ** [comment]
> Thanks for filing @zuntilZ! That means the provided buffer is not a valid JPEG.

No,Image file format is .jpg and type is  image/jpeg . Why the error still occurs?

**Comment by patrickhulce** [comment]
The file extension does not say anything about the files actual contents unfortunately. 

If this is a JPEG that opens in the vast majority of other parsers or editors than we would welcome a copy of the file to try it here. But 99/100 this error means the buffer passed to jpeg-js was malformed.
